name: CD - Deploy with Terraform

on:
  workflow_run:
    workflows: ["CI - Buld image and push in ecr"]   
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1


      # Install Terraform
      
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.0

     
      # Terraform Init
      - name: Terraform Init
        run: |
          cd ECS-Terraform-infra-task-8
          terraform init \
          -backend-config="bucket=rakesh.s3bucketpearlthoughts" \
          -backend-config="key=${PROJECT_NAME}-task-8-cloudwatch-terraform.tfstate" \
          -backend-config="region=$AWS_REGION"

      # Terraform Plan
      - name: Terraform Plan
        run: |
          cd ECS-Terraform-infra-task-8
          terraform plan \
          -var="image_tag=${IMAGE_TAG}" \
          -var="region=${AWS_REGION}" \
          -var="db_username=${{ secrets.DB_USERNAME }}" \
          -var="db_password=${{ secrets.DB_PASSWORD }}"

      # Terraform Apply
      - name: Terraform Apply
        run: |
          cd ECS-Terraform-infra-task-8
          terraform apply -auto-approve \
          -var="image_tag=${IMAGE_TAG}" \
          -var="region=${AWS_REGION}" \
          -var="db_username=${{ secrets.DB_USERNAME }}" \
          -var="db_password=${{ secrets.DB_PASSWORD }}"
